### ISSUE TITLE
Comparision to Core 2

### ISSUE THREAD

**Issue by beojan** [graysky2/kernel_gcc_patch#24]
You show comparisons of each optimized kernel to the generic kernel, but since the core 2 optimizations apply to all the other CPUs, shouldn't you compare them to the core2 optimized kernel instead?

**Comment by graysky2** [comment]
I don't think so since the point is to offer more microarch options.

**Comment by beojan** [comment]
The new options are supersets of the core2 instruction set, so you need to
show that the additional instructions offer a statistically significant
performance boost over the best officially supported option (i.e. core2),
not just over plain x86_64 generic.

**Comment by graysky2** [comment]
Perhaps, but it's not clear to me that the make end point is gives the most bang.  I don't have much free time these days, but you're welcome to conduct your own tests.

**Comment by Ferroin** [comment]
@beojan Have you looked at why Core 2 is an option?  They have it because the Intel Core microarchitecture is sufficiently different from most other micro-arches that the generic option gives poor performance on processors that implement it.  On a modern Skylake or Ryzen CPU however, the Core 2 option actually gives _worse_ performance, by a pretty significant margin in fact.  IOW, I would expect almost everything this patch adds to show better performance on the intended CPU than the Core 2 option does on the exact same CPU.
